import Head from "next/head";
import Image from "next/image";
import styles from "src/styles/Home.module.css";
import { useEffect, useCallback, useState } from "react";
import { Footer } from "src/COmponents/Footer";
export default function About() {
	const [array, setArray] = useState([]);
	const [list, setList] = useState([]);
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}></main>

			<Footer />
		</div>
	);
}
