import Head from "next/head";
import styles from "src/styles/Home.module.css";
import { Footer } from "src/COmponents/Footer";
import { Header } from "src/COmponents/Header";
import { Profile } from "src/COmponents/Profile";
import Link from "next/link";

export default function Blog() {
	return (
		<div className="flex flex-1 justify-center items-center p-main">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<Profile />
			<Footer />
		</div>
	);
}
