import Head from "next/head";
import styles from "src/styles/Home.module.css";
import { Footer } from "src/COmponents/Footer";
import { Header } from "src/COmponents/Header";
import { Profile } from "src/COmponents/Profile";

export default function Blog() {
	return (
		<div className="p-container">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<div className="min-h-screen flex-col flex-1 items-center justify-center">
				<Profile />
				<Footer />
			</div>
		</div>
	);
}
