import Head from "next/head";
import styles from "src/styles/Home.module.css";
import { Footer } from "src/COmponents/Footer";
import { useState, useEffect, useCallback } from "react";

export default function Home() {
	const [count, setCount] = useState(0);

	const handleClick = (e) => {
		setCount((count) => count + 10);
	};
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1>{count}</h1>
			<button onClick={handleClick}>ぼたん</button>
			<main className={styles.main}>
				<div className=""></div>
			</main>
			<Footer />
		</div>
	);
}
