import Head from "next/head";
import Image from "next/image";
import { Skill } from "src/COmponents/Skill";
import { useState, useEffect, useCallback } from "react";
import { useRouter } from "next/router";
import { Header } from "src/COmponents/Header";
import { Profile } from "src/COmponents/Profile";
import { Footer } from "src/COmponents/Footer";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<div className="min-h-screen p-main flex-1 flex-col justify-center items-center ">
				<Profile />
				<Footer />
			</div>
		</div>
	);
}
